require 'spec'
require File.dirname(__FILE__) + '/../lib/vraptor-scaffold'
require File.dirname(__FILE__) + '/../lib/generators/app_generator'
require File.dirname(__FILE__) + '/../lib/generators/scaffold_generator'
require File.dirname(__FILE__) + '/../lib/generators/attribute'
